#!/usr/bin/env bash

ACTION=$1

javac -d target ./com/hjonas/urlq/URLQ.java
jar cf target/urlq.jar  target/com/hjonas/urlq/*.class

if [[ "$ACTION" == "test" ]]; then
	java -cp urlq.jar:target com.hjonas.urlq.URLQ
fi
